import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';

export interface aws-cdk-rds-s3-postgres-15-integProps extends cdk.StackProps {
  /**
   * Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
   * @default '/cdk-bootstrap/hnb659fds/version'
   */
  readonly bootstrapVersion?: string;
}

export class aws-cdk-rds-s3-postgres-15-integ extends cdk.Stack {
  public constructor(scope: cdk.App, id: string, props: aws-cdk-rds-s3-postgres-15-integProps = {}) {
    super(scope, id, props);

    // Applying default props
    props = {
      ...props,
      bootstrapVersion: new cdk.CfnParameter(this, 'BootstrapVersion', {
        type: 'AWS::SSM::Parameter::Value<String>',
        default: props.bootstrapVersion?.toString() ?? '/cdk-bootstrap/hnb659fds/version',
        description: 'Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]',
      }).valueAsString,
    };

    // Resources
    const importExportBucket642Dd829 = new s3.CfnBucket(this, 'ImportExportBucket642DD829', {
    });
    importExportBucket642Dd829.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.DELETE;

    const postgresDatabaseS3ExportRoleE7b3885c = new iam.CfnRole(this, 'PostgresDatabaseS3ExportRoleE7B3885C', {
      assumeRolePolicyDocument: {
        Statement: [
          {
            Action: 'sts:AssumeRole',
            Effect: 'Allow',
            Principal: {
              Service: 'rds.amazonaws.com',
            },
          },
        ],
        Version: '2012-10-17',
      },
    });

    const postgresDatabaseS3ImportRole4084Fb4d = new iam.CfnRole(this, 'PostgresDatabaseS3ImportRole4084FB4D', {
      assumeRolePolicyDocument: {
        Statement: [
          {
            Action: 'sts:AssumeRole',
            Effect: 'Allow',
            Principal: {
              Service: 'rds.amazonaws.com',
            },
          },
        ],
        Version: '2012-10-17',
      },
    });

    const postgresDatabaseSecret8058A22a = new secretsmanager.CfnSecret(this, 'PostgresDatabaseSecret8058A22A', {
      description: [
        'Generated by the CDK for stack: ',
        this.stackName,
      ].join(''),
      generateSecretString: {
        excludeCharacters: ' %+~`#$&*()|[]{}:;<>?!\'/@\"\\',
        generateStringKey: 'password',
        passwordLength: 30,
        secretStringTemplate: '{\"username\":\"postgres\"}',
      },
    });
    postgresDatabaseSecret8058A22a.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.DELETE;

    const vpcb9e5f0b4 = new ec2.CfnVPC(this, 'VPCB9E5F0B4', {
      cidrBlock: '10.0.0.0/16',
      enableDnsHostnames: true,
      enableDnsSupport: true,
      instanceTenancy: 'default',
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC',
        },
      ],
    });

    const vpcigwb7e252d3 = new ec2.CfnInternetGateway(this, 'VPCIGWB7E252D3', {
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC',
        },
      ],
    });

    const vpcPublicSubnet1Eip6ad938e8 = new ec2.CfnEIP(this, 'VPCPublicSubnet1EIP6AD938E8', {
      domain: 'vpc',
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet1',
        },
      ],
    });

    const vpcPublicSubnet2Eip4947bc00 = new ec2.CfnEIP(this, 'VPCPublicSubnet2EIP4947BC00', {
      domain: 'vpc',
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet2',
        },
      ],
    });

    if (importExportBucket642Dd829 == null) { throw new Error(`A combination of conditions caused 'importExportBucket642Dd829' to be undefined. Fixit.`); }
    if (postgresDatabaseS3ExportRoleE7b3885c == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseS3ExportRoleE7b3885c' to be undefined. Fixit.`); }
    const postgresDatabaseS3ExportRoleDefaultPolicy629F8ccf = new iam.CfnPolicy(this, 'PostgresDatabaseS3ExportRoleDefaultPolicy629F8CCF', {
      policyDocument: {
        Statement: [
          {
            Action: [
              's3:Abort*',
              's3:DeleteObject*',
              's3:GetBucket*',
              's3:GetObject*',
              's3:List*',
              's3:PutObject',
              's3:PutObjectLegalHold',
              's3:PutObjectRetention',
              's3:PutObjectTagging',
              's3:PutObjectVersionTagging',
            ],
            Effect: 'Allow',
            Resource: [
              importExportBucket642Dd829.attrArn,
              [
                importExportBucket642Dd829.attrArn,
                '/*',
              ].join(''),
            ],
          },
        ],
        Version: '2012-10-17',
      },
      policyName: 'PostgresDatabaseS3ExportRoleDefaultPolicy629F8CCF',
      roles: [
        postgresDatabaseS3ExportRoleE7b3885c.ref,
      ],
    });

    if (importExportBucket642Dd829 == null) { throw new Error(`A combination of conditions caused 'importExportBucket642Dd829' to be undefined. Fixit.`); }
    if (postgresDatabaseS3ImportRole4084Fb4d == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseS3ImportRole4084Fb4d' to be undefined. Fixit.`); }
    const postgresDatabaseS3ImportRoleDefaultPolicy3F7a1ad5 = new iam.CfnPolicy(this, 'PostgresDatabaseS3ImportRoleDefaultPolicy3F7A1AD5', {
      policyDocument: {
        Statement: [
          {
            Action: [
              's3:GetBucket*',
              's3:GetObject*',
              's3:List*',
            ],
            Effect: 'Allow',
            Resource: [
              importExportBucket642Dd829.attrArn,
              [
                importExportBucket642Dd829.attrArn,
                '/*',
              ].join(''),
            ],
          },
        ],
        Version: '2012-10-17',
      },
      policyName: 'PostgresDatabaseS3ImportRoleDefaultPolicy3F7A1AD5',
      roles: [
        postgresDatabaseS3ImportRole4084Fb4d.ref,
      ],
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const postgresDatabaseSecurityGroup29446Ef6 = new ec2.CfnSecurityGroup(this, 'PostgresDatabaseSecurityGroup29446EF6', {
      groupDescription: 'RDS security group',
      securityGroupEgress: [
        {
          cidrIp: '0.0.0.0/0',
          description: 'Allow all outbound traffic by default',
          ipProtocol: '-1',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPrivateSubnet1RouteTableBe8a6027 = new ec2.CfnRouteTable(this, 'VPCPrivateSubnet1RouteTableBE8A6027', {
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PrivateSubnet1',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPrivateSubnet1Subnet8Bca10e0 = new ec2.CfnSubnet(this, 'VPCPrivateSubnet1Subnet8BCA10E0', {
      availabilityZone: cdk.Fn.select(0, cdk.Fn.getAzs('')),
      cidrBlock: '10.0.128.0/18',
      mapPublicIpOnLaunch: false,
      tags: [
        {
          key: 'aws-cdk:subnet-name',
          value: 'Private',
        },
        {
          key: 'aws-cdk:subnet-type',
          value: 'Private',
        },
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PrivateSubnet1',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPrivateSubnet2RouteTable0A19e10e = new ec2.CfnRouteTable(this, 'VPCPrivateSubnet2RouteTable0A19E10E', {
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PrivateSubnet2',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPrivateSubnet2SubnetCfcdaa7a = new ec2.CfnSubnet(this, 'VPCPrivateSubnet2SubnetCFCDAA7A', {
      availabilityZone: cdk.Fn.select(1, cdk.Fn.getAzs('')),
      cidrBlock: '10.0.192.0/18',
      mapPublicIpOnLaunch: false,
      tags: [
        {
          key: 'aws-cdk:subnet-name',
          value: 'Private',
        },
        {
          key: 'aws-cdk:subnet-type',
          value: 'Private',
        },
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PrivateSubnet2',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPublicSubnet1RouteTableFee4b781 = new ec2.CfnRouteTable(this, 'VPCPublicSubnet1RouteTableFEE4B781', {
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet1',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPublicSubnet1SubnetB4246d30 = new ec2.CfnSubnet(this, 'VPCPublicSubnet1SubnetB4246D30', {
      availabilityZone: cdk.Fn.select(0, cdk.Fn.getAzs('')),
      cidrBlock: '10.0.0.0/18',
      mapPublicIpOnLaunch: true,
      tags: [
        {
          key: 'aws-cdk:subnet-name',
          value: 'Public',
        },
        {
          key: 'aws-cdk:subnet-type',
          value: 'Public',
        },
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet1',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPublicSubnet2RouteTable6F1a15f1 = new ec2.CfnRouteTable(this, 'VPCPublicSubnet2RouteTable6F1A15F1', {
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet2',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    const vpcPublicSubnet2Subnet74179F39 = new ec2.CfnSubnet(this, 'VPCPublicSubnet2Subnet74179F39', {
      availabilityZone: cdk.Fn.select(1, cdk.Fn.getAzs('')),
      cidrBlock: '10.0.64.0/18',
      mapPublicIpOnLaunch: true,
      tags: [
        {
          key: 'aws-cdk:subnet-name',
          value: 'Public',
        },
        {
          key: 'aws-cdk:subnet-type',
          value: 'Public',
        },
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet2',
        },
      ],
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcb9e5f0b4 == null) { throw new Error(`A combination of conditions caused 'vpcb9e5f0b4' to be undefined. Fixit.`); }
    if (vpcigwb7e252d3 == null) { throw new Error(`A combination of conditions caused 'vpcigwb7e252d3' to be undefined. Fixit.`); }
    const vpcvpcgw99b986dc = new ec2.CfnVPCGatewayAttachment(this, 'VPCVPCGW99B986DC', {
      internetGatewayId: vpcigwb7e252d3.ref,
      vpcId: vpcb9e5f0b4.ref,
    });

    if (vpcPrivateSubnet1Subnet8Bca10e0 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1Subnet8Bca10e0' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2SubnetCfcdaa7a == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2SubnetCfcdaa7a' to be undefined. Fixit.`); }
    const postgresDatabaseSubnets7Dd9954c = new rds.CfnDBSubnetGroup(this, 'PostgresDatabaseSubnets7DD9954C', {
      dbSubnetGroupDescription: 'Subnets for PostgresDatabase database',
      subnetIds: [
        vpcPrivateSubnet1Subnet8Bca10e0.ref,
        vpcPrivateSubnet2SubnetCfcdaa7a.ref,
      ],
    });

    if (vpcPrivateSubnet1RouteTableBe8a6027 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1RouteTableBe8a6027' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet1Subnet8Bca10e0 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1Subnet8Bca10e0' to be undefined. Fixit.`); }
    const vpcPrivateSubnet1RouteTableAssociation347902D1 = new ec2.CfnSubnetRouteTableAssociation(this, 'VPCPrivateSubnet1RouteTableAssociation347902D1', {
      routeTableId: vpcPrivateSubnet1RouteTableBe8a6027.ref,
      subnetId: vpcPrivateSubnet1Subnet8Bca10e0.ref,
    });

    if (vpcPrivateSubnet2RouteTable0A19e10e == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2RouteTable0A19e10e' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2SubnetCfcdaa7a == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2SubnetCfcdaa7a' to be undefined. Fixit.`); }
    const vpcPrivateSubnet2RouteTableAssociation0C73d413 = new ec2.CfnSubnetRouteTableAssociation(this, 'VPCPrivateSubnet2RouteTableAssociation0C73D413', {
      routeTableId: vpcPrivateSubnet2RouteTable0A19e10e.ref,
      subnetId: vpcPrivateSubnet2SubnetCfcdaa7a.ref,
    });

    if (vpcigwb7e252d3 == null) { throw new Error(`A combination of conditions caused 'vpcigwb7e252d3' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1RouteTableFee4b781 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1RouteTableFee4b781' to be undefined. Fixit.`); }
    if (vpcvpcgw99b986dc == null) { throw new Error(`A combination of conditions caused 'vpcvpcgw99b986dc' to be undefined. Fixit.`); }
    const vpcPublicSubnet1DefaultRoute91Cef279 = new ec2.CfnRoute(this, 'VPCPublicSubnet1DefaultRoute91CEF279', {
      destinationCidrBlock: '0.0.0.0/0',
      gatewayId: vpcigwb7e252d3.ref,
      routeTableId: vpcPublicSubnet1RouteTableFee4b781.ref,
    });
    vpcPublicSubnet1DefaultRoute91Cef279.addDependency(vpcvpcgw99b986dc);

    if (vpcPublicSubnet1RouteTableFee4b781 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1RouteTableFee4b781' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1SubnetB4246d30 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1SubnetB4246d30' to be undefined. Fixit.`); }
    const vpcPublicSubnet1RouteTableAssociation0B0896dc = new ec2.CfnSubnetRouteTableAssociation(this, 'VPCPublicSubnet1RouteTableAssociation0B0896DC', {
      routeTableId: vpcPublicSubnet1RouteTableFee4b781.ref,
      subnetId: vpcPublicSubnet1SubnetB4246d30.ref,
    });

    if (vpcigwb7e252d3 == null) { throw new Error(`A combination of conditions caused 'vpcigwb7e252d3' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2RouteTable6F1a15f1 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2RouteTable6F1a15f1' to be undefined. Fixit.`); }
    if (vpcvpcgw99b986dc == null) { throw new Error(`A combination of conditions caused 'vpcvpcgw99b986dc' to be undefined. Fixit.`); }
    const vpcPublicSubnet2DefaultRouteB7481bba = new ec2.CfnRoute(this, 'VPCPublicSubnet2DefaultRouteB7481BBA', {
      destinationCidrBlock: '0.0.0.0/0',
      gatewayId: vpcigwb7e252d3.ref,
      routeTableId: vpcPublicSubnet2RouteTable6F1a15f1.ref,
    });
    vpcPublicSubnet2DefaultRouteB7481bba.addDependency(vpcvpcgw99b986dc);

    if (vpcPublicSubnet2RouteTable6F1a15f1 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2RouteTable6F1a15f1' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2Subnet74179F39 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2Subnet74179F39' to be undefined. Fixit.`); }
    const vpcPublicSubnet2RouteTableAssociation5A808732 = new ec2.CfnSubnetRouteTableAssociation(this, 'VPCPublicSubnet2RouteTableAssociation5A808732', {
      routeTableId: vpcPublicSubnet2RouteTable6F1a15f1.ref,
      subnetId: vpcPublicSubnet2Subnet74179F39.ref,
    });

    if (postgresDatabaseS3ExportRoleE7b3885c == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseS3ExportRoleE7b3885c' to be undefined. Fixit.`); }
    if (postgresDatabaseS3ImportRole4084Fb4d == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseS3ImportRole4084Fb4d' to be undefined. Fixit.`); }
    if (postgresDatabaseSecret8058A22a == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSecret8058A22a' to be undefined. Fixit.`); }
    if (postgresDatabaseSecurityGroup29446Ef6 == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSecurityGroup29446Ef6' to be undefined. Fixit.`); }
    if (postgresDatabaseSubnets7Dd9954c == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSubnets7Dd9954c' to be undefined. Fixit.`); }
    const postgresDatabase0A8a7373 = new rds.CfnDBCluster(this, 'PostgresDatabase0A8A7373', {
      associatedRoles: [
        {
          featureName: 's3Import',
          roleArn: postgresDatabaseS3ImportRole4084Fb4d.attrArn,
        },
        {
          featureName: 's3Export',
          roleArn: postgresDatabaseS3ExportRoleE7b3885c.attrArn,
        },
      ],
      copyTagsToSnapshot: true,
      dbClusterParameterGroupName: 'default.aurora-postgresql15',
      dbSubnetGroupName: postgresDatabaseSubnets7Dd9954c.ref,
      engine: 'aurora-postgresql',
      engineVersion: '15.3',
      masterUserPassword: [
        '{{resolve:secretsmanager:',
        postgresDatabaseSecret8058A22a.ref,
        ':SecretString:password::}}',
      ].join(''),
      masterUsername: [
        '{{resolve:secretsmanager:',
        postgresDatabaseSecret8058A22a.ref,
        ':SecretString:username::}}',
      ].join(''),
      port: 5432,
      vpcSecurityGroupIds: [
        postgresDatabaseSecurityGroup29446Ef6.attrGroupId,
      ],
    });
    postgresDatabase0A8a7373.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.SNAPSHOT;

    if (vpcPublicSubnet1DefaultRoute91Cef279 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1DefaultRoute91Cef279' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1Eip6ad938e8 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1Eip6ad938e8' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1RouteTableAssociation0B0896dc == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1RouteTableAssociation0B0896dc' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1SubnetB4246d30 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1SubnetB4246d30' to be undefined. Fixit.`); }
    const vpcPublicSubnet1NatGatewayE0556630 = new ec2.CfnNatGateway(this, 'VPCPublicSubnet1NATGatewayE0556630', {
      allocationId: vpcPublicSubnet1Eip6ad938e8.attrAllocationId,
      subnetId: vpcPublicSubnet1SubnetB4246d30.ref,
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet1',
        },
      ],
    });
    vpcPublicSubnet1NatGatewayE0556630.addDependency(vpcPublicSubnet1DefaultRoute91Cef279);
    vpcPublicSubnet1NatGatewayE0556630.addDependency(vpcPublicSubnet1RouteTableAssociation0B0896dc);

    if (vpcPublicSubnet2DefaultRouteB7481bba == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2DefaultRouteB7481bba' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2Eip4947bc00 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2Eip4947bc00' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2RouteTableAssociation5A808732 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2RouteTableAssociation5A808732' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2Subnet74179F39 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2Subnet74179F39' to be undefined. Fixit.`); }
    const vpcPublicSubnet2NatGateway3C070193 = new ec2.CfnNatGateway(this, 'VPCPublicSubnet2NATGateway3C070193', {
      allocationId: vpcPublicSubnet2Eip4947bc00.attrAllocationId,
      subnetId: vpcPublicSubnet2Subnet74179F39.ref,
      tags: [
        {
          key: 'Name',
          value: 'aws-cdk-rds-s3-postgres-15-integ/VPC/PublicSubnet2',
        },
      ],
    });
    vpcPublicSubnet2NatGateway3C070193.addDependency(vpcPublicSubnet2DefaultRouteB7481bba);
    vpcPublicSubnet2NatGateway3C070193.addDependency(vpcPublicSubnet2RouteTableAssociation5A808732);

    if (postgresDatabase0A8a7373 == null) { throw new Error(`A combination of conditions caused 'postgresDatabase0A8a7373' to be undefined. Fixit.`); }
    if (postgresDatabaseSecret8058A22a == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSecret8058A22a' to be undefined. Fixit.`); }
    const postgresDatabaseSecretAttachment25D11930 = new secretsmanager.CfnSecretTargetAttachment(this, 'PostgresDatabaseSecretAttachment25D11930', {
      secretId: postgresDatabaseSecret8058A22a.ref,
      targetId: postgresDatabase0A8a7373.ref,
      targetType: 'AWS::RDS::DBCluster',
    });

    if (vpcPrivateSubnet1RouteTableBe8a6027 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1RouteTableBe8a6027' to be undefined. Fixit.`); }
    if (vpcPublicSubnet1NatGatewayE0556630 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet1NatGatewayE0556630' to be undefined. Fixit.`); }
    const vpcPrivateSubnet1DefaultRouteAe1d6490 = new ec2.CfnRoute(this, 'VPCPrivateSubnet1DefaultRouteAE1D6490', {
      destinationCidrBlock: '0.0.0.0/0',
      natGatewayId: vpcPublicSubnet1NatGatewayE0556630.ref,
      routeTableId: vpcPrivateSubnet1RouteTableBe8a6027.ref,
    });

    if (vpcPrivateSubnet2RouteTable0A19e10e == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2RouteTable0A19e10e' to be undefined. Fixit.`); }
    if (vpcPublicSubnet2NatGateway3C070193 == null) { throw new Error(`A combination of conditions caused 'vpcPublicSubnet2NatGateway3C070193' to be undefined. Fixit.`); }
    const vpcPrivateSubnet2DefaultRouteF4f5cfd2 = new ec2.CfnRoute(this, 'VPCPrivateSubnet2DefaultRouteF4F5CFD2', {
      destinationCidrBlock: '0.0.0.0/0',
      natGatewayId: vpcPublicSubnet2NatGateway3C070193.ref,
      routeTableId: vpcPrivateSubnet2RouteTable0A19e10e.ref,
    });

    if (postgresDatabase0A8a7373 == null) { throw new Error(`A combination of conditions caused 'postgresDatabase0A8a7373' to be undefined. Fixit.`); }
    if (postgresDatabaseSubnets7Dd9954c == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSubnets7Dd9954c' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet1DefaultRouteAe1d6490 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1DefaultRouteAe1d6490' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet1RouteTableAssociation347902D1 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1RouteTableAssociation347902D1' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2DefaultRouteF4f5cfd2 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2DefaultRouteF4f5cfd2' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2RouteTableAssociation0C73d413 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2RouteTableAssociation0C73d413' to be undefined. Fixit.`); }
    const postgresDatabaseReaderInstance70A1ad02 = new rds.CfnDBInstance(this, 'PostgresDatabaseReaderInstance70A1AD02', {
      dbClusterIdentifier: postgresDatabase0A8a7373.ref,
      dbInstanceClass: 'db.t3.medium',
      dbSubnetGroupName: postgresDatabaseSubnets7Dd9954c.ref,
      engine: 'aurora-postgresql',
    });
    postgresDatabaseReaderInstance70A1ad02.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.DELETE;
    postgresDatabaseReaderInstance70A1ad02.addDependency(vpcPrivateSubnet1DefaultRouteAe1d6490);
    postgresDatabaseReaderInstance70A1ad02.addDependency(vpcPrivateSubnet1RouteTableAssociation347902D1);
    postgresDatabaseReaderInstance70A1ad02.addDependency(vpcPrivateSubnet2DefaultRouteF4f5cfd2);
    postgresDatabaseReaderInstance70A1ad02.addDependency(vpcPrivateSubnet2RouteTableAssociation0C73d413);

    if (postgresDatabase0A8a7373 == null) { throw new Error(`A combination of conditions caused 'postgresDatabase0A8a7373' to be undefined. Fixit.`); }
    if (postgresDatabaseSubnets7Dd9954c == null) { throw new Error(`A combination of conditions caused 'postgresDatabaseSubnets7Dd9954c' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet1DefaultRouteAe1d6490 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1DefaultRouteAe1d6490' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet1RouteTableAssociation347902D1 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet1RouteTableAssociation347902D1' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2DefaultRouteF4f5cfd2 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2DefaultRouteF4f5cfd2' to be undefined. Fixit.`); }
    if (vpcPrivateSubnet2RouteTableAssociation0C73d413 == null) { throw new Error(`A combination of conditions caused 'vpcPrivateSubnet2RouteTableAssociation0C73d413' to be undefined. Fixit.`); }
    const postgresDatabaseWriterInstance3Fa5d5e7 = new rds.CfnDBInstance(this, 'PostgresDatabaseWriterInstance3FA5D5E7', {
      dbClusterIdentifier: postgresDatabase0A8a7373.ref,
      dbInstanceClass: 'db.t3.medium',
      dbSubnetGroupName: postgresDatabaseSubnets7Dd9954c.ref,
      engine: 'aurora-postgresql',
    });
    postgresDatabaseWriterInstance3Fa5d5e7.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.DELETE;
    postgresDatabaseWriterInstance3Fa5d5e7.addDependency(vpcPrivateSubnet1DefaultRouteAe1d6490);
    postgresDatabaseWriterInstance3Fa5d5e7.addDependency(vpcPrivateSubnet1RouteTableAssociation347902D1);
    postgresDatabaseWriterInstance3Fa5d5e7.addDependency(vpcPrivateSubnet2DefaultRouteF4f5cfd2);
    postgresDatabaseWriterInstance3Fa5d5e7.addDependency(vpcPrivateSubnet2RouteTableAssociation0C73d413);
  }
}

